### ISSUE TITLE
Correct Badge Style

### ISSUE THREAD

**Issue by tstreamDOTh** [tstreamDOTh/firebase-swiss#33]
<img width="263" alt="Screenshot 2019-10-13 at 12 57 06 AM" src="https://user-images.githubusercontent.com/11137394/66706753-722b8000-ed54-11e9-98fd-16534f25bbc8.png">
Just remove the style query parameter from the badge link

**Comment by Zihfred** [comment]
Can i get this task?

**Comment by Zihfred** [comment]
https://img.shields.io/badge/all_contributors-6-orange.svg?style=flat-square 
from this link?
