### ISSUE TITLE
Update Exception Message

### ISSUE THREAD

**Issue by tstreamDOTh** [tstreamDOTh/firebase-swiss#8]
If invalid type is passed to FireFunctions, the exception message is `'Invalid Type! allowed Types - CREATE, GET, PATCH'`, Also include `DELETE` in the message, firebase-swiss supports delete operation as well

**Comment by CoryWritesCode** [comment]
I can take this.

**Comment by naclcaleb** [comment]
Wow, you beat me by 2 seconds 😆

**Comment by tstreamDOTh** [comment]
@naclcaleb Haha, there will be more issues coming up on this repo 😁

**Comment by tstreamDOTh** [comment]
Resolved
